
title:               ZG+CD
tagline:             got married
baseurl:             https://zgandcd.github.io
permalink:           :title/

pages_list:       
  Announcement: 'https://www.nytimes.com/2018/09/02/fashion/weddings/zoe-guengerich-connor-dowd.html'
  Old Site: 'https://web.archive.org/web/20180821125924/https://www.zoeandconnor.com/'
  Reviews: '/reviews'
  Pictures: '/pics'

sass:
  sass_dir:          _sass
  style:            :compressed

author:
  name:              ZGCD
  url:               zgandcd.github.io

gems:
  - jekyll-sitemap
  - jekyll-gist

