
title:               ZG+CD
tagline:             got married
baseurl:             https://zgandcd.github.io
permalink:           :title/

pages_list:       
  Reviews: '/reviews'
  Pictures: '/pictures'

sass:
  sass_dir:          _sass
  style:            :compressed

author:
  name:              ZGCD
  url:               zgandcd.github.io

gems:
  - jekyll-sitemap
  - jekyll-gist

